name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      # Step 3: Upgrade dependencies to latest compatible versions
      - name: Upgrade dependencies
        run: flutter pub upgrade

      # Step 4: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 5: Clean Flutter project
      - name: Clean Flutter Project
        run: flutter clean

      # Step 6: Build the Flutter web app
      - name: Build Flutter Web
        run: flutter build web --release  # Build the web app in release mode

      # Step 7: Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_QUIZAPP_36D3B }}
          channelId: live
          projectId: quizapp-36d3b
